language: python
sudo: required
dist: trusty
before_install:
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended latexmk
  - sudo add-apt-repository -y ppa:inkscape.dev/stable && sudo apt-get -q update && sudo apt-get -y install inkscape

install:
  - pip install -r requirements.txt

script:
  - export LATEXOPTS="--interaction=nonstopmode"
  - ( cd cores/cv32e40p/user_manual && sphinx-build -M html source build -nWT )
  - ( cd cores/cv32e40p/user_manual && sphinx-build -M latexpdf source build -nWT )
